import math

WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT = 1000, 900
FPS = 120


SHIP_WIDTH = 10
SHIP_HALF_WIDTH = SHIP_WIDTH/2
SHIP_HEIGHT = 15
SHIP_HALF_HEIGHT = SHIP_HEIGHT/2
SHIP_C = math.sqrt((SHIP_WIDTH/2)**2 + (SHIP_HEIGHT/2)**2)
SHIP_ALFA = 180 - math.degrees(math.atan((SHIP_WIDTH/2)/(SHIP_HEIGHT/2)))

SHIP_ACCELERATION = 0.5
SHIP_DEACCELERATION = 0.1
SHIP_MAX_SPEED = 3
SHIP_ROTATE_SPEED = 2

SCORE_GAIN = 100
SCORE_FONT = "Agency FB"
SCORE_FONT_SIZE = 30
SCORE_TOP = 20
SCORE_LEFT = 30


BULLET_SPEED = 7


ASTEROID_SPEED = 1.5
SPAWN_ANGLE_RANGE = 60
SPAWN_CHANCE = 0.01
